# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 380, 541, 361))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 20, 521, 331))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(300, 10, 451, 361))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 431, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 271, 361))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 20, 241, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setProperty("value", 20)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 380, 641, 361))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 621, 331))
        self.textBrowser.setObjectName("textBrowser")

        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(760, 10, 451, 361))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 30, 431, 321))
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionf = QtWidgets.QAction(MainWindow)
        self.actionf.setObjectName("actionf")
        self.actionf_2 = QtWidgets.QAction(MainWindow)
        self.actionf_2.setObjectName("actionf_2")
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actiona_2 = QtWidgets.QAction(MainWindow)
        self.actiona_2.setObjectName("actiona_2")
        self.actiona_3 = QtWidgets.QAction(MainWindow)
        self.actiona_3.setObjectName("actiona_3")
        self.actionxiug = QtWidgets.QAction(MainWindow)
        self.actionxiug.setObjectName("actionxiug")
        self.actiona_4 = QtWidgets.QAction(MainWindow)
        self.actiona_4.setObjectName("actiona_4")
        self.actiona_5 = QtWidgets.QAction(MainWindow)
        self.actiona_5.setObjectName("actiona_5")
        self.actiona_6 = QtWidgets.QAction(MainWindow)
        self.actiona_6.setObjectName("actiona_6")
        self.actiona_7 = QtWidgets.QAction(MainWindow)
        self.actiona_7.setObjectName("actiona_7")
        self.actiona_8 = QtWidgets.QAction(MainWindow)
        self.actiona_8.setObjectName("actiona_8")
        self.actiona_9 = QtWidgets.QAction(MainWindow)
        self.actiona_9.setObjectName("actiona_9")
        self.menu_4.addAction(self.actiona)
        self.menu_4.addAction(self.actionxiug)
        self.menu_4.addAction(self.actiona_3)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.actiona_2)
        self.menu_5.addAction(self.actiona_4)
        self.menu_5.addAction(self.actiona_8)
        self.menu_5.addAction(self.actiona_6)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.actiona_5)
        self.menu_5.addAction(self.actiona_9)
        self.menu_5.addAction(self.actiona_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "彩色图像"))
        self.groupBox_3.setTitle(_translate("MainWindow", "深度图像"))
        self.groupBox_4.setTitle(_translate("MainWindow", "配置"))
        self.label.setText(_translate("MainWindow", "图像配置"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.checkBox_3.setText(_translate("MainWindow", "彩色图像"))
        self.checkBox_2.setText(_translate("MainWindow", "红外IR图像"))
        self.checkBox.setText(_translate("MainWindow", "深度图像"))
        self.label_2.setText(_translate("MainWindow", "帧率配置"))
        self.label_3.setText(_translate("MainWindow", "帧率："))
        self.label_4.setText(_translate("MainWindow", "FPS"))
        self.pushButton_4.setText(_translate("MainWindow", "确定"))
        self.label_7.setText(_translate("MainWindow", "数据选择"))
        self.pushButton_2.setText(_translate("MainWindow", "上传深度图"))
        self.pushButton_5.setText(_translate("MainWindow", "上传数据集"))
        self.pushButton_3.setText(_translate("MainWindow", "保存当前帧"))
        self.groupBox_5.setTitle(_translate("MainWindow", "控制台"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:10.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "红外IR图像"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "连接"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.menu_4.setTitle(_translate("MainWindow", "算法"))
        self.menu_5.setTitle(_translate("MainWindow", "数据"))
        self.actionf.setText(_translate("MainWindow", "算法注册"))
        self.actionf_2.setText(_translate("MainWindow", "f"))
        self.actiona.setText(_translate("MainWindow", "注册算法"))
        self.actiona_2.setText(_translate("MainWindow", "算法推理"))
        self.actiona_3.setText(_translate("MainWindow", "删除算法"))
        self.actionxiug.setText(_translate("MainWindow", "修改算法"))
        self.actiona_4.setText(_translate("MainWindow", "上传深度图"))
        self.actiona_5.setText(_translate("MainWindow", "上传数据集"))
        self.actiona_6.setText(_translate("MainWindow", "删除深度图"))
        self.actiona_7.setText(_translate("MainWindow", "删除数据集"))
        self.actiona_8.setText(_translate("MainWindow", "修改深度图"))
        self.actiona_9.setText(_translate("MainWindow", "修改数据集"))

        out_text = \
'''[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
Kinect serial: 000042615043
Kinect firmware: 4.0.3921.0
<capsule object "IRCameraParams" at 0x7ff34e77e9c0>
[Info] [OpenGLDepthPacketProcessor] avg. time: 10.7439ms -> ~72.3298HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 19.3728ms -> ~50.2748HZ
[Info] [OpenGLDepthPacketProcessor] avg. time: 11.2656ms -> ~73.8677HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 20.4378ms -> ~52.1323HZ
[Info] [OpenGLDepthPacketProcessor] avg. time: 10.3867ms -> ~71.9648HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 21.8763ms -> ~52.9826HZ
[Info] [OpenGLDepthPacketProcessor] avg. time: 9.8909ms -> ~70.3509HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 22.4122ms -> ~51.5398HZ
[Info] [OpenGLDepthPacketProcessor] avg. time: 10.9661ms -> ~71.9082HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 20.0013ms -> ~50.2741HZ
[Info] [OpenGLDepthPacketProcessor] avg. time: 10.0523ms -> ~72.0828HZ
[Info] [TurboJpegRgbPacketProcessor] avg. time: 19.4699ms -> ~51.0921HZ
'''

        # [Info] [OpenGLDepthPacketProcessor] avg. time: 10.0523ms -> ~72.0828HZ
        # [Info] [TurboJpegRgbPacketProcessor] avg. time: 19.4699ms -> ~51.0921HZ
        # [Info] [OpenGLDepthPacketProcessor] avg. time: 11.6749ms -> ~72.0914HZ
        # [Info] [TurboJpegRgbPacketProcessor] avg. time: 20.6478ms -> ~49.9081HZ

        out_text = \
'''libva info: VA-API version 1.7.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[Error] [VaapiRgbPacketProcessorImpl] vaInitialize(display, &major_ver, &minor_ver): unknown libva error
Packet pipeline: OpenGLPacketPipeline
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 7 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:3 with serial 018135364647
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Debug] [Freenect2DeviceImpl] status 0x090000: 9729
[Debug] [Freenect2DeviceImpl] status 0x090000: 9731
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Debug] [DepthPacketStreamParser] not all subsequences received 0
[Info] [Freenect2DeviceImpl] started
[Debug] [DepthPacketStreamParser] not all subsequences received 896
[Info] [OpenGLDepthPacketProcessor] avg. time: 5.13121ms -> ~194.886Hz
[Info] [TurboJpegRgbPacketProcessor] avg. time: 20.5397ms -> ~48.6863Hz
[Info] [OpenGLDepthPacketProcessor] avg. time: 4.47638ms -> ~223.395Hz
[Info] [TurboJpegRgbPacketProcessor] avg. time: 11.3802ms -> ~87.8716Hz
[Info] [OpenGLDepthPacketProcessor] avg. time: 3.72459ms -> ~268.486Hz
[Info] [OpenGLDepthPacketProcessor] avg. time: 4.04903ms -> ~246.973Hz
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] releasing usb interfaces...
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] already closed, doing nothing
'''

        self.textBrowser.setText(out_text)


